#!/usr/bin/env node
const Markov = require('markov-strings');

// Compiled by http://www.bobrosslipsum.com/ 2016 January
// Liberally taken from https://github.com/rusty-software/bobrosslipsum
const phrases = [
  "Sometimes the brush is lazy.",
  "This is the lazy man's way of painting.",
  "Use what happens naturally.",
  "Don't want to set these clouds on fire.",
  "You can end up with great big cotton balls in the sky if you're not careful.",
  "Learn to control it.",
  "Make big billowy, fluffy clouds.",
  "Just sorta work it around and around here.",
  "We want this swirling, churning actions here.",
  "Keep this brush moving all the time.",
  "Now we're ready to start working it.",
  "Always doing the things furthest away first and working forward.",
  "Always follow the angles here.",
  "It's cold, but it's beautiful.",
  "See how easy that was?",
  "It's very easy to make a sky darker, but it's a son of a gun to make it lighter.",
  "Another thing that seems to give us a lot of problems is almighty clouds.",
  "Now we'll fluff it.",
  "Now, very gently, we'll hypnotize it.",
  "Everybody likes mountains.",
  "Always follow the angles.",
  "See? I knew you could do it!",
  "Talent is a pursued interest.",
  "Anything you are willing to practice, you can do!",
  "I used to work for weeks to make a tree.",
  "We are really trying to teach you a technique. We're not trying to teach you to copy.",
  "Let your imagination be your guide.",
  "Do whatever feels right.",
  "There's no big secret to this.",
  "Oh, the agony! I remember it.",
  "I'm a nature freak.",
  "You need to understand nature.",
  "We spend so much of our lives looking, but never, never seeing.",
  "That's the most fun of all.",
  "Just mix it up real good.",
  "Now let's use the fan brush.",
  "You just sort of have to make almighty decisions.",
  "Every series, we need to have a crazy day.",
  "We're ready to get serious with this.",
  "See how far away that looks already?",
  "We'll start playing a little bit.",
  "I love to make trees.",
  "Use your imagination.",
  "We're gonna give him some buns to sit on.",
  "Talent is nothing more than a pursued interest.",
  "It should give you a lot of ideas of a lot of crazy things you can do.",
  "Just let it bounce around and play.",
  "Let's build a happy little cloud in the sky.",
  "You can do all this blending without becoming a mud-mixer.",
  "It's too far away.",
  "Painting used to drive me crazy.",
  "It takes a very, very little bit.",
  "Every time you add another plane, you create more depth.",
  "Just walk right back into this painting.",
  "Look at all those... thousands of leaves!",
  "You could sit there with your one-haired brush for a week trying to do that, or you can do it in one stroke with an almighty brush!",
  "Don't be afraid of it.",
  "Don't worry about it; have fun with it!",
  "All you need is a dream in your heart.",
  "Get a nice, even distribution of paint all through the bristles.",
  "Let's just sort of play a little color here and there.",
  "I'm always looking for a nice, easy way to do this.",
  "If you're gonna do mountains, it's fun to have little bumps on them here and there.",
  "All you're doing here is whisper-light.",
  "If you over-mix it, you just get one dead color.",
  "We never duplicate anything exactly.",
  "You can always add more if you want it.",
  "Brush mix!",
  "Don't let your trees get too symmetrical... too even.",
  "All these little things make it interesting.",
  "Find out which one works best for you, and that's the one that you want to use.",
  "Angles are very, very important.",
  "This is your dirt, so you put it where you want it.",
  "I want to do something that's just a little bit different, and I think you'll find it's fun.",
  "Start with a small amount and blend upward.",
  "You can begin making all kinds of beautiful shapes up in the sky.",
  "Let the brush play and have fun -- let it go!",
  "Chickens need a place to live too.",
  "Use a color that's a little more muted and quiet.",
  "Let's have some fun today.",
  "Give this ol' windmill a leg!",
  "Don't be afraid of this big brush.",
  "Let us know, and we'll do some more crazy things for you.",
  "Ready to go!",
  "Just let it go, have fun.",
  "Leave some open spots here and there.",
  "Only takes a minute.",
  "He lives right there -- that's his home.",
  "Try not to kill it.",
  "However you want to change this, that's the way it should be.",
  "Now we can start picking out some individual things.",
  "Here and there and there and here.",
  "Let's work on that tree right there.",
  "You don't want it to be flat.",
  "All these fantastic things... they just sorta happen.",
  "You can blend this until it absolutely goes away and leaves you.",
  "Get it to where you want it, and leave it alone.",
  "Don't piddle with them -- don't worry about them.",
  "It's always trying to go somewhere that it can be level.",
  "Feel the power of the water.",
  "We'll make those decisions later.",
  "Take right off today!",
  "Let some little things just shine through.",
  "Leave a little area open here.",
  "That's why I like it so much.",
  "Just dance it around.",
  "Keep it moving.",
  "We're looking for happy little clouds.",
  "Sort of mix it up.",
  "Get tough with it.",
  "We planned this son-of-a-gun right from the beginning.",
  "You wouldn't buy somebody else's mistakes; nobody's going to buy yours.",
  "Think like a tree when you do these.",
  "I want some happy little things happening up here in the sky.",
  "Help them make a happy buck or two.",
  "That knife's a little big... let me get my small knife.",
  "Let 'em have it!",
  "Follow these angles.",
  "Don't want to overkill.",
  "That gives us a general idea of how that mountain was made.",
  "That son-of-a-gun is growing on us!",
  "Give him some arms -- a tree needs some arms.",
  "Blend color right here on the canvas.",
  "Don't want to set the sky on fire.",
  "Be sure it's odorless or you'll be working by yourself.",
  "You do it the way that you want it.",
  "Use a lot of pressure.",
  "All you're worried about is this nice outside shape.",
  "Very soft, very quiet.",
  "We all need a friend.",
  "Make friends with trees.",
  "Don't get carried away.",
  "Let it sort of bounce around and play.",
  "Be... so... careful!",
  "Let's build us a mountain!",
  "We'll make some big ol' huge mountains!",
  "Pretend you're a whisper floating across here.",
  "Wiggle it, then sharpen it.",
  "Oh dear, here comes a tree!",
  "When the birds take over, I'll have friends!",
  "As usual, Bob's gonna do a big tree.",
  "Just leave that space open.",
  "Drop in some happy little shadows.",
  "He's a healthy cloud.",
  "Just sorta stir it up, don't overdo -- just enough to bring it together.",
  "We're just looking for a nice, basic, outside shape. We could care less what's going on inside here.",
  "Water breaks, and it churns, and it has fun!",
  "Hit it, and get away from it.",
  "We're looking for a nice, even distribution of color.",
  "Let's have some big, fluffy clouds in this painting.",
  "We'll just sort of slip in some clouds.",
  "You have to sort of plan these clouds.",
  "You do whatever works for you.",
  "Create that little fuzzy look.",
  "Don't worry about it -- just sort of throw it in.",
  "Big buildings are just little buildings that had a shot of vitamins.",
  "We don't know where that goes.",
  "Go out and spend some time talking to a tree.",
  "Trees are nice people.",
  "Just make little X's, and we'll put in a happy little sky.",
  "Pull from the outside in.",
  "Let's make some big, fluffy clouds today!",
  "You have to make an almighty decision.",
  "They are restricted only by your imagination.",
  "Pretend that if you're not careful your hand will literally just float away.",
  "It's just a game of angles.",
  "If there's a secret to anything, it's practice.",
  "Just practice, and you really can do this.",
  "And that easy, we've got a happy mountain.",
  "Painting does not have to be difficult.",
  "Dance in a happy little sky.",
  "One of our golden rules is that thin paint will stick to thick paint.",
  "Be careful with this bright red -- it'll eat up your whole world in a heartbeat.",
  "Think like a cloud.",
  "Don't overwork -- be lazy!",
  "Get strong with it.",
  "If there's any secret to this technique, or any other technique: it's practice.",
  "It doesn't take much, but you have to devote that time.",
  "Let's go on up here and let's get started.",
  "Just sorta twist in a little sky.",
  "Blend it all together and have fun with it.",
  "Tongue got over my teeth there and I couldn't see what I was saying.",
  "I would put water in just about everything.",
  "Wind this up and blend it together.",
  "Clouds could very well be the freest things in nature.",
  "Let 'em have fun.",
  "The round brush is so fun, let's go back to that.",
  "As long as you have fun and learn from it, nothing is wasted.",
  "If you want to be good at anything, you have to practice.",
  "Let's put in a happy little sky.",
  "Just make little criss-cross strokes.",
  "See how easy that is?",
  "This piece of canvas is your world.",
  "They just sort of bounce around and have fun up there.",
  "You really cannot make a mistake here.",
  "Today, we have to make a big decision.",
  "They think you're magic!",
  "Just sorta rock back and forth.",
  "Just sorta make these things up in your mind, and let them drop in.",
  "We use darkness to make those colors stand out!",
  "That's one of those happy accidents.",
  "Your artist license gives you complete freedom.",
  "A place you want to go and run through bare-footed.",
  "This is such a super day!",
  "These are far away, and I'm not looking for a lot of detail.",
  "I don't know if you can ever make a pet out of an alligator, but I had an alligator who lived with me.",
  "It helps, when you're doing these kinds of things, make up little stories in your mind.",
  "This is where the whole ecosystem starts.",
  "We're like drug dealers -- we come into town and get people absolutely addicted to painting.",
  "It doesn't hurt anybody, everybody's happy, and it brings a lot of joy to people.",
  "We have to have some fun.",
  "It takes very little color.",
  "Drop in a happy little sky here.",
  "Everything should get lighter toward the horizon.",
  "I think we'll put a happy little cloud up in the sky.",
  "Maybe this is the same cloud.",
  "There's some little stringy ones that live down here.",
  "Give it a lift-upper.",
  "Show it who's boss!",
  "You're limited only by your imagination.",
  "I like to be able to create my own world.",
  "All kinds of beautiful little things just happen.",
  "Sing along as you're doing this.",
  "That's the job I want in my next life -- I wanna come back and be a cloud and just float around and have a good time.",
  "That's a fantastic little cloud.",
  "Create the illusion.",
  "It'll open whole new worlds for you once you learn to make friends with this knife.",
  "Cover a couple of cameramen, and we're in business!",
  "Son of a gun, it looks like we've got two big eyes on there.",
  "This is how you make a giant cartoon figure.",
  "That's what makes it fun! Just enjoy!",
  "I just like to wash brushes.",
  "Where do the clouds live in your world?",
  "Everybody needs to sing in the sunshine!",
  "Just like baking a cake!",
  "Learn to work with anything that happens.",
  "You knew it was there all the time.",
  "Let's make this a little more interesting.",
  "We don't want to overload it, just a little bit.",
  "I'm lazy... I look for easy ways to do things.",
  "That blue is so strong, it'll eat up your whole world in a heartbeat.",
  "...three hairs and some air...",
  "Don't let this get too strong or it'll stand out.",
  "You have unlimited power here.",
  "You can create any illusion that you can conceive in your mind.",
  "Don't fight these things -- allow them to happen.",
  "Just tap. Give it that little push.",
  "If you're going to knock a wasp's nest down, you run.",
  "Have to have dark in order to show light.",
  "A thin, and let me say that again, a THIN layer of liquid clear.",
  "Always keep the brush moving.",
  "Use that to your advantage.",
  "Don't just cover it all up -- leave these spots!",
  "Mountains come in all shapes and sizes.",
  "Learn to use this knife, and you won't believe what it can do!",
  "You have to make friends with it.",
  "Devote a little time to working with it.",
  "Maybe we will have a little moon up here.",
  "People are so excited when they see this happen.",
  "Always start with a clean brush in a light area and work outward.",
  "We'll just take the brush strokes out.",
  "The other thing that is so fantastic about painting is that it teaches you to see.",
  "Don't over do it -- be careful. Be careful.",
  "Just follow your imagination.",
  "We can stir this up a little bit.",
  "You can continue to blend it until it just goes away.",
  "Begin laying in just some beautiful little highlights.",
  "There's nothing worse than an angry tree.",
  "I want this one a little bit darker.",
  "Do you want to get crazy?",
  "I think we'll just do a happy little picture today.",
  "We'll have a super time.",
  "Let's make some happy little clouds in our world.",
  "Wherever you think they should be, then that's exactly where they should be.",
  "Wind it up, blend it together.",
  "I am a fanatic for water.",
  "(chuckles) Just beat the devil out of it.",
  "This is where you take out all your frustrations and all your hostilities, and just have a good time.",
  "All we're trying to do is teach you a technique and turn you loose on the world.",
  "We use no patterns, and no tracings.",
  "All we do is just sorta have an idea in our mind, and we just sorta let it happen.",
  "You learn to take advantage of whatever happens and use it to make your painting special.",
  "Mix it up, just like you're making a cake or something.",
  "...two hairs and some air...",
  "Let's get crazy.",
  "I don't want a lot of mountains today.",
  "That's about all we need.",
  "Look at your painting and make a decision.",
  "I lived in Alaska for many, many years.",
  "This is a very individual thing, painting is.",
  "It's easy to add more color, but it's a son of a gun to take it away.",
  "Very gently go across the entire sky.",
  "...right on the edge of the blade...",
  "Everybody will see nature through different eyes",
  "Everybody has their own idea of what a mountain should look like.",
  "Let it float right down the side of the mountain.",
  "Zooooom... you've gotta make the little noises or it doesn't work right.",
  "Painting is as individual as people are.",
  "At some point in between, you have to reach a happy medium.",
  "I'll bet you didn't realize you had that much power.",
  "You can do anything that you want to do... you can move mountains!",
  "You can determine what your world is like.",
  "Let's just have a good time.",
  "Today's such a wonderful day, let's just make a happy little painting.",
  "Nothing to it.",
  "A very quiet little sky.",
  "You know me -- I like water.",
  "Think about form and shape -- how do you want this thing to be?",
  "A half a hair and some air.",
  "Beautiful little roundy-hill-type things.",
  "A flock of trees? I don't know... a STAND of trees. That's what you call them!",
  "Let's really have some fun.",
  "Now things are going to start happening.",
  "You'll be amazed at some of the effects you can achieve.",
  "It's very hard to see your painting when you're right up against it.",
  "We become mud-mixers.",
  "Maybe there's a happy little tree... he lives right there.",
  "The more that you practice, the more you're able to visualize things.",
  "You know me, I get crazy.",
  "I want to darken the edges.",
  "Fun time! Now we wash the ol' brush!",
  "Let's build us a little cloud.",
  "Don't just throw it up there and think that a cloud will appear.",
  "That was so much fun! Let's get crazy!",
  "You want to be able to control these rascals.",
  "Just make it up.",
  "You've got to have a little sadness once in awhile to let you know when the good times come.",
  "I thought today, this would be our crazy painting.",
  "I think you'll be tickled with what you can do with something that starts out looking this bad.",
  "Just gonna start any ol' where.",
  "You'll be amazed at what you can do if you'll just try.",
  "Practice visualizing things in your mind.",
  "Don't be afraid to experiment.",
  "You're gonna have one WILD day!",
  "The birds would get sort of crazy.",
  "Stir them up a little, then blend them.",
  "If everything was good all the time, pretty soon you'd be accepting that as normal.",
  "You decide where all these things are.",
  "There's too many complicated things in our life already.",
  "That's the fun part of this whole technique.",
  "Really be stingy with it.",
  "The just do nice things for you.",
  "You don't have to tell them you did this with a paper towel.",
  "Enough of that.",
  "They are very special. Take care of those!",
  "Quiet, quiet little bushes.",
  "A place for all the little creatures to put their money.",
  "We don't know exactly where this is gonna go, and we don't care at this point.",
  "In the woods, you have all different colors of green.",
  "Don't be afraid to have a lot of greens.",
  " That's pretty already, shoot... but we're not gonna stop there.",
  "Just let it sorta dance around in the sky.",
  "We'll put a few little nicety things in there.",
  "Clouds have form and shape and life and are interesting, they're not just ol' dull clouds.",
  "When I finally got to Alaska, whew boy, I just went crazy",
  "The only thing I'm good at is falling down.",
  "I look for easy ways to do things.",
  "Say all that with a mouthful of rocks.",
  "I'll show you exactly the kind of messes we get into sometimes.",
  "I really don't know what we're gonna do except have some fun.",
  "Painters are expected to be different.",
  "Remember where your finger's been before you scratch your nose.",
  "Don't be afraid to experiment.",
  "Don't be afraid to go out on a limb once in a while.",
  "Where are we going with this?",
  "Just have a good feeling... be happy, and in love with your life and your world.",
  "Let's get right to it.",
  "This is one that you can do.",
  "That simple, that easy!",
  "We'll just sort of see what happens.",
  "That'll be a challenge!",
  "Let's have a big cloud!",
  "It's a lot of fun.",
  "Nothing to it!",
  "It's bad when you have to tie a bucket on the side of your painting.",
  "Time to get crazy now!",
  "You'd better get out your big coat and put it on.",
  "You know I'm crazy about water.",
  "Let's have some fun!",
  "Make your own mind up about where your clouds should live.",
  "Looks like there's a storm coming already.",
  "You have to make these big decisions in your world.",
  "You have unlimited power here.",
  "You can do anything that you believe you can do.",
  "Don't think there's anybody that doesn't like mountains. Well, maybe there is.",
  "Time to get crazy.",
  "Everybody should have a friend.",
  "If you learn to make one tree, you can make a million trees.",
  "It's the contrast in this painting that makes it so pretty.",
  "Very, very... let me say that one more time: very.",
  "The smallest, very little amount.",
  "Tell you what: let's get crazy today.",
  "You can change your mind right mid stream.",
  "I want a very gentle, quiet little sky.",
  "Today, I want softness in our world... tranquility, quiet, peaceful.",
  "Whatever works is good.",
  "Let's do a winter scene, what the heck.",
  "Maybe I'll have a bit mountain today.",
  "Life's wonderful, isn't it?",
  "Let's make a wild mountain today.",
  "If we make a boo-boo, it's right here -- but that's alright, because we don't make mistakes in our world.",
  "You know what? Let's get crazy.",
  "He's got the leanies!",
  "Let's just do a painting that's fun.",
  "Allow the colors to blend together.",
  "It'll just eat up all the crimson in the world.",
  "We don't care.",
  "He just hangs around back there and has a good time all day.",
  "Just a nice little mountain, a little friendly guy.",
  "It doesn't matter in our world where it goes.",
  "I like the mountains -- they're my favorite.",
  "You can just go on and on and on.",
  "Absolutely no limits!",
  "The joy of painting really is universal.",
  "We've got a conglomeration going on there!",
  "Sometimes we get crazy here.",
  "Now a little rabbit can hide down there and look over at us!",
  "Let's just have some fun today.",
  "Let me put a little on the other side too, we don't want it to feel left out.",
  "Just sort of blend it around.",
  "I want this to be very bright right in here.",
  "I don't know exactly what they are, and I don't really care at this point.",
  "Just let your imagination take you to anywhere you want to be.",
  "Shh... our secret! Don't tell, just enjoy!",
  "Who knows? Get crazy!",
  "Let's just enjoy today.",
  "Anything that happens here, we can live with and we can turn it into something that looks pretty good most of the time.",
  "Fun time!",
  "That's exactly where it should be.",
  "That's about enough right there.",
  "Isn't life wonderful?",
  "Throw in some happy little things wherever you want them.",
  "You make the big decisions where all these things live in your world.",
  "Take your time and play with these things.",
  "We don't know where it goes.",
  "Let's do another one -- what the heck!",
  "All you do is just go back with it.",
  "You don't have to work at it hardly at all.",
  "Highlight a few of these rascals.",
  "Great time!",
  "Get nervous.",
  "You know me -- I love water.",
  "Let's do a happy little mountain.",
  "Just let it float.",
  "You make the big decisions.",
  "We're not too worried about it today.",
  "Painting offers freedom.",
  "Bravery test!",
  "Shoot, I've got to get a little crazy.",
  "It's a fantastic day here!",
  "A winter scene that's very warm, very pretty, and will just make you feel good.",
  "We'll just have a firecracker of a sky up here.",
  "Let them have a good time in your world.",
  "The cloud needs a little friend.",
  "Just let it sort of run across here, wherever you want it to go.",
  "Cherish it! Take care of it!",
  "Think about some basic shapes and forms in this -- don't just throw them on at random.",
  "Do a cabin-ectomy.",
  "I like big trees.",
  "It's a fantastic day here, and I hope it is wherever you're at.",
  "We'll let our imaginations take us wherever we want to go today.",
  "Anything that happens here, you can work with it.",
  "You can do anything you desire on this canvas.",
  "You can do it!",
  "You have to make all these big decisions when you have power.",
  "You didn't know you had so much power, did you?",
  "Art is an expression of self.",
  "If you comply with that rule, how can you go wrong?",
  "So many things you can create.",
  "Sort of an orangy-yellowish color.",
  "OK, let's have some fun!",
  "Just decide basically where you wanna start, and off you go!",
  "The titles comes out of there, it sounds like an old car.",
  "He's like the rest of us -- he's about half crazy.",
  "Just go around and try them all.",
  "That rascal's sneaky!",
  "You decide -- you have to make these big decisions.",
  "Let's get crazy here.",
  "Don't want much... don't want much...",
  "Everybody should paint what they see and what they feel.",
  "A lot of things happening right here.",
  "A beautiful little sunset.",
  "A big strong tree needs big strong roots.",
  "A fan brush is a fantastic piece of equipment. Use it. Make friends with it.",
  "A happy cloud.",
  "A little happy sunlight shining through there.",
  "A thin paint will stick to a thick paint.",
  "A tree cannot be straight if it has a crooked trunk.",
  "A tree needs to be your friend if you're going to paint him.",
  "Absolutely no pressure. You are just a whisper floating across a mountain.",
  "All kinds of happy little splashes.",
  "All you have to do is let your imagination go wild.",
  "All you have to learn here is how to have fun.",
  "All you need to paint is a few tools, a little instruction, and a vision in your mind.",
  "Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying.",
  "And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right.",
  "And I will hypnotize that just a little bit.",
  "And just raise cain.",
  "And right there you got an almighty cloud.",
  "And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.",
  "Any little thing can be your friend if you let it be.",
  "Anyone can paint.",
  "Anything you want to do you can do here.",
  "Anytime you learn something your time and energy are not wasted.",
  "As trees get older they lose their chlorophyll.",
  "At home you have unlimited time.",
  "Automatically, all of these beautiful, beautiful things will happen.",
  "Be brave.",
  "Be careful. You can always add more - but you can't take it away.",
  "Be so very light. Be a gentle whisper.",
  "Brown is such a nice color.",
  "But they're very easily killed. Clouds are delicate.",
  "But we're not there yet, so we don't need to worry about it.",
  "Clouds are free they come and go as they please.",
  "Clouds are free. They just float around the sky all day and have fun.",
  "Decide where your cloud lives. Maybe he lives right in here.",
  "Didn't you know you had that much power? You can move mountains. You can do anything.",
  "Do an almighty painting with us.",
  "Don't be afraid to make these big decisions. Once you start, they sort of just make themselves.",
  "Don't be bashful drop me a line.",
  "Don't fiddle with it all day.",
  "Don't fight it, use what happens.",
  "Don't forget to tell these special people in your life just how special they are to you.",
  "Don't hurry. Take your time and enjoy.",
  "Don't kill all your dark areas - you need them to show the light.",
  "Each highlight must have it's own private shadow.",
  "Even the worst thing we can do here is good.",
  "Even trees need a friend. We all need friends.",
  "Every day I learn.",
  "Every highlight needs it's own personal shadow.",
  "Every single thing in the world has its own personality - and it is up to you to make friends with the little rascals.",
  "Every time you practice, you learn more.",
  "Everybody needs a friend.",
  "Everybody's different. Trees are different. Let them all be individuals.",
  "Everyone is going to see things differently - and that's the way it should be.",
  "Everyone needs a friend. Friends are the most valuable things in the world.",
  "Everyone wants to enjoy the good parts - but you have to build the framework first.",
  "Everything is happy if you choose to make it that way.",
  "Everything's not great in life, but we can still find beauty in it.",
  "Exercising the imagination, experimenting with talents, being creative; these things, to me, are truly the windows to your soul.",
  "Fluff it up a little and hypnotize it.",
  "Fluff that up.",
  "Follow the lay of the land. It's most important.",
  "For the lack of a better word I call them hangy downs.",
  "From all of us here, I want to wish you happy painting and God bless, my friends.",
  "Get away from those little Christmas tree things we used to make in school.",
  "Get tough with it, get strong.",
  "Go out on a limb - that's where the fruit is.",
  "God gave you this gift of imagination. Use it.",
  "Happy painting, God bless.",
  "Have fun with it.",
  "Here we're limited by the time we have.",
  "Here's something that's fun.",
  "How do you make a round circle with a square knife? That's your challenge for the day.",
  "How to paint. That's easy. What to paint. That's much harder.",
  "I can't think of anything more rewarding than being able to express yourself to others through painting.",
  "I get carried away with this brush cleaning.",
  "I guess I'm a little weird. I like to talk to trees and animals. That's okay though; I have more fun than most people.",
  "I guess that would be considered a UFO. A big cotton ball in the sky.",
  "I like to beat the brush.",
  "I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush.",
  "I really recommend you use odorless thinner or your spouse is gonna run you right out into the yard and you'll be working by yourself.",
  "I sincerely wish for you every possible joy life could bring.",
  "I spend a lot of time walking around in the woods and talking to trees, and squirrels, and little rabbits and stuff.",
  "I started painting as a hobby when I was little. I didn't know I had any talent. I believe talent is just a pursued interest. Anybody can do what I do.",
  "I think there's an artist hidden in the bottom of every single one of us.",
  "I thought today we would do a happy little picture.",
  "I thought today we would make a happy little stream that's just running through the woods here.",
  "I want everbody to be happy. That's what it's all about.",
  "I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things.",
  "I will take some magic white, and a little bit of Vandyke brown and a little touch of yellow.",
  "I'll go over the colors one more time that we use: Titanium white, Thalo green, Prussian blue, Van Dyke brown, Alizarin crimson, Sap green, Cad yellow, and Permanent red.",
  "I'm a water fanatic. I love water.",
  "I'm going to mix up a little color. We'll use Van Dyke Brown, Permanent Red, and a little bit of Prussian Blue.",
  "I'm gonna start with a little Alizarin crimson and a touch of Prussian blue",
  "I'm sort of a softy, I couldn't shoot Bambi except with a camera.",
  "If I paint something, I don't want to have to explain what it is.",
  "If it's not what you want - stop and change it. Don't just keep going and expect it will get better.",
  "If there's two big trees invariably sooner or later there's gonna be a little tree.",
  "If these lines aren't straight, your water's going to run right out of your painting and get your floor wet.",
  "If we're going to have animals around we all have to be concerned about them and take care of them.",
  "If we're gonna walk though the woods, we need a little path.",
  "If what you're doing doesn't make you happy - you're doing the wrong thing.",
  "If you didn't have baby clouds, you wouldn't have big clouds.",
  "If you do too much it's going to lose its effectiveness.",
  "If you don't like it - change it. It's your world.",
  "If you don't think every day is a good day - try missing a few. You'll see.",
  "If you hypnotize it, it will go away.",
  "If you overwork it you become a cloud killer. There's nothing worse than a cloud killer.",
  "If you've been in Alaska less than a year you're a Cheechako.",
  "Imagination is the key to painting.",
  "In life you need colors.",
  "In nature, dead trees are just as normal as live trees.",
  "In painting, you have unlimited power. You have the ability to move mountains. You can bend rivers. But when I get home, the only thing I have power over is the garbage.",
  "In this world, everything can be happy.",
  "In your imagination you can go anywhere you want.",
  "In your world you can create anything you desire.",
  "In your world you have total and absolute power.",
  "Isn't it fantastic that you can change your mind and create all these happy things?",
  "Isn't it great to do something you can't fail at?",
  "Isn't that fantastic that you can create an almighty tree that fast?",
  "Isn't that fantastic?",
  "Isn't that fantastic? You can just push a little tree out of your brush like that.",
  "It is a lot of fun.",
  "It just happens - whether or not you worried about it or tried to plan it.",
  "It looks so good, I might as well not stop.",
  "It's a good way of getting rid of all your anxieties and hostilities.",
  "It's a super day, so why not make a beautiful sky?",
  "It's a very cold picture, I may have to go get my coat. It's about to freeze me to death.",
  "It's almost like something out of a fairytale book.",
  "It's amazing what you can do with a little love in your heart.",
  "It's beautiful - and we haven't even done anything to it yet.",
  "It's cold, but it's beautiful.",
  "It's hard to see things when you're too close. Take a step back and look.",
  "It's important to me that you're happy.",
  "It's life. It's interesting. It's fun.",
  "It's so important to do something every day that will make you happy.",
  "Just a happy little shadow that lives in there.",
  "Just beat the devil out of it.",
  "Just go back and put one little more happy tree in there.",
  "Just go out and talk to a tree. Make friends with it.",
  "Just let go - and fall like a little waterfall.",
  "Just let this happen. We just let this flow right out of our minds.",
  "Just let your mind wander and enjoy. This should make you happy.",
  "Just make a decision and let it go.",
  "Just make little strokes like that.",
  "Just pretend you are a whisper floating across a mountain.",
  "Just relax and let it flow. That easy.",
  "Just take out whatever you don't want. It'll change your entire perspective.",
  "Just think about these things in your mind - then bring them into your world.",
  "Just think about these things in your mind and drop em' on canvas.",
  "Just use the old one inch brush.",
  "La- da- da- da- dah. Just be happy.",
  "Learn when to stop.",
  "Let all these little things happen. Don't fight them. Learn to use them.",
  "Let all these things just sort of happen.",
  "Let that brush dance around there and play.",
  "Let the paint work.",
  "Let your heart be your guide.",
  "Let your heart take you to wherever you want to be.",
  "Let your imagination be your guide.",
  "Let your imagination be your guide.",
  "Let's build an almighty mountain.",
  "Let's build some happy little clouds up here.",
  "Let's do it again then, what the heck.",
  "Let's do that again.",
  "Let's get crazy.",
  "Let's get wild today.",
  "Let's give him a friend too. Everybody needs a friend.",
  "Let's go up in here, and start having some fun",
  "Let's have a happy little tree in here.",
  "Let's have a little bit of fun today.",
  "Let's have a nice tree right here.",
  "Let's make a happy little mountain now.",
  "Let's make a nice big leafy tree.",
  "Let's make some happy little clouds in our world.",
  "Let's make some happy little clouds in our world.",
  "Let's put a touch more of the magic here.",
  "Let's put some happy little bushes on the other side now.",
  "Let's put some happy little clouds in our world.",
  "Let's put some happy trees and bushes back in here.",
  "Let's put some highlights on these little trees. The sun wouldn't forget them.",
  "Life is too short to be alone, too precious. Share it with a friend.",
  "Little trees and bushes grow however makes them happy.",
  "Look around, look at what we have. Beauty is everywhere, you only have to look to see it.",
  "Making all those little fluffies that live in the clouds.",
  "Maybe he has a little friend that lives right over here.",
  "Maybe there was an old trapper that lived out here and maybe one day he went to check his beaver traps, and maybe he fell into the river and drowned.",
  "Maybe there's a happy little Evergreen that lives here.",
  "Maybe there's a happy little bush that lives right there.",
  "Maybe there's a happy little waterfall happening over here.",
  "Maybe there's a little something happening right here.",
  "Maybe we got a few little happy bushes here, just covered with snow.",
  "Mix your color marbly don't mix it dead.",
  "Nature is so fantastic, enjoy it. Let it make you happy.",
  "Nice little clouds playing around in the sky.",
  "Nice little fluffy clouds laying around in the sky being lazy.",
  "No pressure. Just relax and watch it happen.",
  "No worries. No cares. Just float and wait for the wind to blow you around.",
  "Nothing wrong with washing your brush.",
  "Nothing's gonna make your husband or wife madder than coming home and having a snow-covered dinner.",
  "Now it's beginning to make a little sense.",
  "Now let's put some happy little clouds in here.",
  "Now then, let's play.",
  "Now we can begin working on lots of happy little things.",
  "Now we don't want him to get lonely, so we'll give him a little friend.",
  "Now we'll take the almighty fan brush.",
  "Now, we're going to fluff this cloud.",
  "Of course he's a happy little stone, cause we don't have any other kind.",
  "Once you learn the technique, ohhh! Turn you loose on the world; you become a tiger.",
  "Only God can make a tree - but you can paint one.",
  "Only eight colors that you need.",
  "Only think about one thing at a time. Don't get greedy.",
  "Paint anything you want on the canvas. Create your own world.",
  "Painting should do one thing. It should put happiness in your heart.",
  "Poor old tree.",
  "Pretend you're water. Just floating without any effort. Having a good day.",
  "Put it in, leave it alone.",
  "Put light against light - you have nothing. Put dark against dark - you have nothing. It's the contrast of light and dark that each give the other one meaning.",
  "Put your feelings into it, your heart, it's your world.",
  "Remember how free clouds are. They just lay around in the sky all day long.",
  "See how easy it is to create a little tree right in your world.",
  "See there how easy that is.",
  "See there, told you that would be easy.",
  "See. We take the corner of the brush and let it play back-and-forth.",
  "So often we avoid running water, and running water is a lot of fun.",
  "Sometimes you learn more from your mistakes than you do from your masterpieces.",
  "Son of a gun.",
  "Steve wants reflections, so let's give him reflections.",
  "Take your time. Speed will come later.",
  "Talent is a pursued interest. That is to say, anything you practice you can do.",
  "Talk to trees, look at the birds. Whatever it takes.",
  "That is when you can experience true joy, when you have no fear.",
  "That's a crooked tree. We'll send him to Washington.",
  "That's a son of a gun of a cloud.",
  "That's crazy.",
  "That's the way I look when I get home late; black and blue.",
  "That's what makes life fun. That you can make these decisions. That you can create the world that you want.",
  "That's what painting is all about. It should make you feel good when you paint.",
  "That's why I paint - because I can create the kind of world I want - and I can make this world as happy as I want it.",
  "The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start.",
  "The least little bit can do so much.",
  "The light is your friend. Preserve it.",
  "The little tiny Tim easels will let you down.",
  "The man who does the best job is the one who is happy at his job.",
  "The more we do this - the more it will do good things to our heart.",
  "The only prerequisite is that it makes you happy. If it makes you happy then it's good.",
  "The only thing worse than yellow snow is green snow.",
  "The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe.",
  "The shadows are just like the highlights, but we're going in the opposite direction.",
  "The very fact that you're aware of suffering is enough reason to be overjoyed that you're alive and can experience it.",
  "There are no limits in this world.",
  "There are no mistakes. You can fix anything that happens.",
  "There comes a nice little fluffer.",
  "There is immense joy in just watching - watching all the little creatures in nature.",
  "There is no right or wrong - as long as it makes you happy and doesn't hurt anyone.",
  "There isn't a rule. You just practice and find out which way works best for you.",
  "There it is.",
  "There we go.",
  "There's not a thing in the world wrong with washing your brush.",
  "There's nothing wrong with having a tree as a friend.",
  "These little son of a guns hide in your brush and you just have to push them out.",
  "These things happen automatically. All you have to do is just let them happen.",
  "These trees are so much fun. I get started on them and I have a hard time stopping.",
  "They say everything looks better with odd numbers of things. But sometimes I put even numbers--just to upset the critics.",
  "Think about a cloud. Just float around and be there.",
  "This is a happy place, little squirrels live here and play.",
  "This is an example of what you can do with just a few things, a little imagination and a happy dream in your heart.",
  "This is gonna be a happy little seascape.",
  "This is probably the greatest thing that's ever happened in my life.",
  "This is probably the greatest thing to happen in my life - to be able to share this with you.",
  "This is the fun part",
  "This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.",
  "This is the way you take out your flustrations.",
  "This is truly an almighty mountain.",
  "This is unplanned it really just happens.",
  "This is where you take out all your hostilities and frustrations. It's better than kicking the puppy dog around and all that so.",
  "This is your creation - and it's just as unique and special as you are.",
  "This is your world, whatever makes you happy you can put in it. Go crazy.",
  "This is your world.",
  "This painting comes right out of your heart.",
  "This piece of canvas is your world.",
  "This present moment is perfect simply due to the fact you're experiencing it.",
  "Those great big fluffy clouds.",
  "Tree trunks grow however makes them happy.",
  "Trees cover up a multitude of sins.",
  "Trees get lonely too, so we'll give him a little friend.",
  "Trees grow however makes them happy.",
  "Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect.",
  "Trees live in your fan brush, but you have to scare them out.",
  "Use absolutely no pressure. Just like an angel's wing.",
  "Use what happens naturally, don't fight it.",
  "Use what you see, don't plan it.",
  "Use your imagination, let it go.",
  "Van Dyke Brown is a very nice brown, it's almost like a chocolate brown.",
  "Very easy to work these to death.",
  "Volunteering your time; it pays you and your whole community fantastic dividends.",
  "Water's like me. It's laaazy... Boy, it always looks for the easiest way to do things",
  "We artists are a different breed of people. We're a happy bunch.",
  "We can always carry this a step further. There's really no end to this.",
  "We can fix anything.",
  "We don't have anything but happy trees here.",
  "We don't have to be committed. We are just playing here.",
  "We don't have to be concerned about it. We just have to let it fall where it will.",
  "We don't make mistakes we just have happy little accidents.",
  "We don't need any guidelines or formats. All we need to do is just let it flow right out of us.",
  "We don't really know where this goes - and I'm not sure we really care.",
  "We don't want to set these clouds on fire.",
  "We have a fantastic little sky!",
  "We have all at one time or another mixed some mud.",
  "We have no limits to our world. We're only limited by our imagination.",
  "We might as well make some Almighty mountains today as well, what the heck.",
  "We must be quiet, soft and gentle.",
  "We need dark in order to show light.",
  "We spend so much of our life looking - but never seeing.",
  "We start with a vision in our heart, and we put it one canvas.",
  "We tell people sometimes: we're like drug dealers, come into town and get everybody absolutely addicted to painting. It doesn't take much to get you addicted.",
  "We want to use a lot pressure while using no pressure at all.",
  "We wash our brush with odorless thinner.",
  "We'll do another happy little painting.",
  "We'll have a super time.",
  "We'll lay all these little funky little things in there.",
  "We'll make some happy little bushes here.",
  "We'll paint one happy little tree right here.",
  "We'll play with clouds today.",
  "We'll put all the little clouds in and let them dance around and have fun.",
  "We'll put some happy little leaves here and there.",
  "We'll take a little bit of Van Dyke Brown.",
  "We'll throw some old gray clouds in here just sneaking around and having fun.",
  "We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world.",
  "We're trying to teach you a technique here and how to use it.",
  "What the devil.",
  "When things happen - enjoy them. They're little gifts.",
  "When you buy that first tube of paint it gives you an artist license.",
  "When you do it your way you can go anywhere you choose.",
  "With practice comes confidence.",
  "With something so strong, a little bit can go a long way.",
  "Work on one thing at a time. Don't get carried away - we have plenty of time.",
  "Work that paint.",
  "Working it up and down, back and forth.",
  "You are only limited by your imagination.",
  "You better get your coat out, this is going to be a cold painting.",
  "You can create anything that makes you happy.",
  "You can create beautiful things - but you have to see them in your mind first.",
  "You can create the world you want to see and be a part of. You have that power.",
  "You can do anything here - the only prerequisite is that it makes you happy.",
  "You can do anything here. So don't worry about it.",
  "You can do anything your heart can imagine.",
  "You can do it.",
  "You can get away with a lot.",
  "You can spend all day playing with mountains.",
  "You can work and carry-on and put lots of little happy things in here.",
  "You can't have light without dark. You can't know happiness unless you've known sorrow.",
  "You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it.",
  "You could sit here for weeks with your one hair brush trying to do that - or you could do it with one stroke with an almighty brush.",
  "You create the dream - then you bring it into your world.",
  "You don't have to be crazy to do this but it does help.",
  "You don't have to spend all your time thinking about what you're doing, you just let it happen.",
  "You don't want to kill all your dark areas they are very important.",
  "You got your heavy coat out yet? It's getting colder.",
  "You gotta think like a tree.",
  "You have freedom here. The only guide is your heart.",
  "You have to allow the paint to break to make it beautiful.",
  "You have to make almighty decisions when you're the creator.",
  "You have to make these big decisions.",
  "You have to make those little noises or it won't work.",
  "You need the dark in order to show the light.",
  "You want your tree to have some character. Make it special.",
  "You're meant to have fun in life.",
  "You're the greatest thing that has ever been or ever will be. You're special. You're so very special.",
  "You've got to learn to fight the temptation to resist these things. Just let them happen."
];

const markov = new Markov(phrases);
markov.buildCorpusSync();
const result = markov.generateSentenceSync();
console.log(result['string']);
